### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by bobo66597** [GrokCV/SeRankDet#3]
尊敬的作者您好，我阅读了您的论文，对于TABLE VI的实验结果存在一点疑问，您对于NUDT-SIRST数据集的训练和测试集的划分比例是多少？是按照1：1的比例划分，还是其他的划分方法。

**Comment by YimianDai** [comment]
谢谢您的提醒！

我们后面会上传 split 文件

**Comment by bobo66597** [comment]
> 谢谢您的提醒！
> 
> 我们后面会上传 split 文件

好的，非常感谢您的回复
